name: Build macOS Project with Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Import certificates and provisioning profiles
        run: |
          echo "$CI_SECRET_CERTIFICATE_PASSWORD" | security unlock-keychain -p - ${CI_SECRET_CERTIFICATE_KEYCHAIN}
          security import $CI_SECRET_CERTIFICATE_FILE -k ${CI_SECRET_CERTIFICATE_KEYCHAIN}
          security import $CI_SECRET_PROVISIONING_PROFILE_FILE -k ${CI_SECRET_CERTIFICATE_KEYCHAIN}

      - name: Install Firebase
        run: |
          brew install --cask firebase-admin

      - name: Build App
        run: |
          xcodebuild -project src/Gradify.xcodeproj -scheme Gradify -destination 'platform=macOS,arch=x86_64' build -allowProvisioningUpdates
        
    
