name: Build macOS Project with Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
      - name: Install Firebase
        run: |
          brew install firebase-tools

      - name: Build
        run: |
          xcodebuild -project src/Gradify.xcodeproj -scheme Gradify -destination 'platform=macOS,arch=x86_64' build

      - name: Test
        run: |
          xcodebuild -project src/Gradify.xcodeproj -scheme Gradify -destination 'platform=macOS,arch=x86_64' test

      - name: Deploy
        run: |
           firebase deploy
